= JAVA ISO-639-3 support
:toc:

image:https://www.javadoc.io/badge/org.meeuw.i18n/i18n-iso-639-3.svg?color=blue[javadoc,link=https://www.javadoc.io/doc/org.meeuw.i18n/i18n-iso-639-3/latest]
image:https://github.com/mihxil/i18n-iso-639-3/workflows/build/badge.svg?[Build Status,link=https://github.com/mihxil/i18n-iso-639-3/actions?query=workflow/build]
image:https://img.shields.io/maven-central/v/org.meeuw.i18n/i18n-iso-639-3.svg?label=Maven%20Central[Maven Central,link=https://central.sonatype.com/search?namespace=org.meeuw.i18n&name=i18n-iso-639-3]
image:https://img.shields.io/nexus/s/https/oss.sonatype.org/org.meeuw.i18n/i18n-iso-639-3.svg[snapshots,link=https://oss.sonatype.org/content/repositories/snapshots/org/meeuw/i18n/]
image:https://codecov.io/gh/mihxil/i18n-iso-639-3/branch/main/graph/badge.svg[codecov,link=https://codecov.io/gh/mihxil/i18n-iso-639-3]


Codes for Languages of the World are covered by the https://en.wikipedia.org/wiki/ISO_639-3[ISO-639-3 standard]

This standard provides a 3-letter code for each language.

There are too many such codes to be contained in a java-enum (e.g. https://github.com/TakahikoKawasaki/nv-i18n/blob/master/src/main/java/com/neovisionaries/i18n/LanguageAlpha3Code.java is just not complete)

This package has the tab seperated files provided by https://iso639-3.sil.org/, and java classes to read this, and provide all language codes as java objects, with getters.

== Usage

[source, java]
----
import org.meeuw.i18n.languages.LanguageCode;

Optional<LanguageCode> languageCode = LanguageCode.getByCode("nld");

LanguageCode languageCode = LanguageCode.languageCode("nl");

languageCode.getInvertedName();


LanguageCode.stream()
   .sorted();

----

See also the https://github.com/mihxil/i18n-iso-639-3/blob/main/src/test/java/org/meeuw/i18n/languages/test/LanguageCodeTest.java[test cases]
[source, java]
----
include::src/test/java/org/meeuw/i18n/languages/test/LanguageCodeTest.java[]
----

=== Retired codes
`LanguageCode#getByCode` will also support retired codes if possible. This means that the code of the returned object may be different:

[source, java]
----
// the 'krim' dialect (Sierra Leano) officially merged into 'bmf' (Bom-Kim) in 2017

 assertThat(LanguageCode.getByCode("krm").get().getCode()).isEqualTo("bmf");
----

== Support

=== JAXB
The language code is annotated with a JAXB annotation. It will serialize and deserialize to and from the code. The dependency on the annotation is optional.

=== Serializable
The `LanguageCode` is serializable, and ensures that on deserialization the same object for every language is returned. (And only the _code_ is non transient).

=== Sortable

The default sort order of a `LanguageCode` is on 'Inverted Name'.


=== Versions

[cols="1,1,1,1"]
|===
|<1
|developing/testing
|2023
|

|1.x
|compabible with java 8, javax.xml, module-info java 11
|
|

| 1.0
|
| 2023-11-30
|


|2.x
|java 11, jakarta.xml
|2024-01-28
|jakarta mostly applies to the optional jaxb support (and to some - also optional - validation annotations)

|2.1
|support for retired codes
|2024-02-11
|
|===




