
package org.meeuw.i18n.languages;

import java.util.*;

import javax.annotation.processing.Generated;


/**
 * An enum with all ISO-639-1 language codes.
 * <p>
 * This enum is automatically generated by class org.meeuw.i18n.languages.test.GenerateEnumsTest from all ISO-639-3 languages which have a part1 code.
 *
 */
@Generated("org.meeuw.i18n.languages.test.GenerateEnumsTest")
public enum ISO_639_1_Code
    implements LanguageCode
{


    /**
     * {@link ISO_639_3_Code iso 639 3 code}: aar Afar
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    aa,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: abk Abkhazian
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ab,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: ave Avestan
     * <p>
     * scope: individual
     * <p>
     * type: historical
     *
     */
    ae,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: afr Afrikaans
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    af,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: aka Akan
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    ak,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: amh Amharic
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    am,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: arg Aragonese
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    an,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: ara Arabic
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    ar,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: asm Assamese
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    as,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: ava Avaric
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    av,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: aym Aymara
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    ay,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: aze Azerbaijani
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    az,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: bak Bashkir
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ba,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: bel Belarusian
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    be,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: bul Bulgarian
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    bg,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: bis Bislama
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    bi,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: bam Bambara
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    bm,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: ben Bengali
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    bn,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: bod Tibetan
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    bo,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: bre Breton
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    br,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: bos Bosnian
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    bs,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: cat Catalan, Valencian
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ca,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: che Chechen
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ce,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: cha Chamorro
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ch,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: cos Corsican
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    co,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: cre Cree
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    cr,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: ces Czech
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    cs,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: chu Church Slavic, Church Slavonic, Old Bulgarian, Old Church Slavonic, Old Slavonic
     * <p>
     * scope: individual
     * <p>
     * type: historical
     *
     */
    cu,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: chv Chuvash
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    cv,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: cym Welsh
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    cy,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: dan Danish
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    da,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: deu German
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    de,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: div Dhivehi, Divehi, Maldivian
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    dv,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: dzo Dzongkha
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    dz,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: ewe Ewe
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ee,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: ell Modern Greek (1453-)
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    el,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: eng English
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    en,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: epo Esperanto
     * <p>
     * scope: individual
     * <p>
     * type: constructed
     *
     */
    eo,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: spa Castilian, Spanish
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    es,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: est Estonian
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    et,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: eus Basque
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    eu,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: fas Persian
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    fa,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: ful Fulah
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    ff,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: fin Finnish
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    fi,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: fij Fijian
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    fj,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: fao Faroese
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    fo,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: fra French
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    fr,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: fry Western Frisian
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    fy,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: gle Irish
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ga,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: gla Gaelic, Scottish Gaelic
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    gd,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: glg Galician
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    gl,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: grn Guarani
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    gn,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: guj Gujarati
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    gu,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: glv Manx
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    gv,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: hau Hausa
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ha,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: heb Hebrew
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    he,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: hin Hindi
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    hi,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: hmo Hiri Motu
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ho,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: hrv Croatian
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    hr,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: hat Haitian, Haitian Creole
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ht,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: hun Hungarian
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    hu,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: hye Armenian
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    hy,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: her Herero
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    hz,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: ina Interlingua (International Auxiliary Language Association)
     * <p>
     * scope: individual
     * <p>
     * type: constructed
     *
     */
    ia,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: ind Indonesian
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    id,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: ile Interlingue, Occidental
     * <p>
     * scope: individual
     * <p>
     * type: constructed
     *
     */
    ie,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: ibo Igbo
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ig,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: iii Nuosu, Sichuan Yi
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ii,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: ipk Inupiaq
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    ik,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: ido Ido
     * <p>
     * scope: individual
     * <p>
     * type: constructed
     *
     */
    io,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: isl Icelandic
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    is,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: ita Italian
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    it,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: iku Inuktitut
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    iu,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: jpn Japanese
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ja,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: jav Javanese
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    jv,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: kat Georgian
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ka,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: kon Kongo
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    kg,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: kik Gikuyu, Kikuyu
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ki,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: kua Kuanyama, Kwanyama
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    kj,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: kaz Kazakh
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    kk,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: kal Greenlandic, Kalaallisut
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    kl,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: khm Central Khmer, Khmer
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    km,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: kan Kannada
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    kn,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: kor Korean
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ko,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: kau Kanuri
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    kr,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: kas Kashmiri
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ks,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: kur Kurdish
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    ku,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: kom Komi
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    kv,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: cor Cornish
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    kw,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: kir Kirghiz, Kyrgyz
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ky,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: lat Latin
     * <p>
     * scope: individual
     * <p>
     * type: historical
     *
     */
    la,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: ltz Letzeburgesch, Luxembourgish
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    lb,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: lug Ganda
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    lg,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: lim Limburgan, Limburger, Limburgish
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    li,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: lin Lingala
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ln,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: lao Lao
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    lo,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: lit Lithuanian
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    lt,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: lub Luba-Katanga
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    lu,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: lav Latvian
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    lv,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: mlg Malagasy
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    mg,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: mah Marshallese
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    mh,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: mri Maori
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    mi,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: mkd Macedonian
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    mk,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: mal Malayalam
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ml,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: mon Mongolian
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    mn,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: mar Marathi
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    mr,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: msa Malay (macrolanguage)
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    ms,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: mlt Maltese
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    mt,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: mya Burmese
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    my,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: nau Nauru
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    na,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: nob Norwegian Bokmål
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    nb,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: nde North Ndebele
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    nd,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: nep Nepali (macrolanguage)
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    ne,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: ndo Ndonga
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ng,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: nld Dutch, Flemish
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    nl,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: nno Norwegian Nynorsk
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    nn,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: nor Norwegian
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    no,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: nbl South Ndebele
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    nr,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: nav Navaho, Navajo
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    nv,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: nya Chewa, Chichewa, Nyanja
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ny,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: oci Occitan (post 1500)
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    oc,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: oji Ojibwa
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    oj,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: orm Oromo
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    om,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: ori Oriya (macrolanguage)
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    or,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: oss Ossetian, Ossetic
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    os,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: pan Panjabi, Punjabi
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    pa,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: pli Pali
     * <p>
     * scope: individual
     * <p>
     * type: historical
     *
     */
    pi,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: pol Polish
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    pl,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: pus Pashto, Pushto
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    ps,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: por Portuguese
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    pt,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: que Quechua
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    qu,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: roh Romansh
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    rm,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: run Rundi
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    rn,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: ron Moldavian, Moldovan, Romanian
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ro,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: rus Russian
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ru,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: kin Kinyarwanda
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    rw,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: san Sanskrit
     * <p>
     * scope: macrolanguage
     * <p>
     * type: historical
     *
     */
    sa,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: srd Sardinian
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    sc,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: snd Sindhi
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    sd,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: sme Northern Sami
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    se,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: sag Sango
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    sg,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: hbs Serbo-Croatian
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     * <p>
     * Code element for 639-1 has been deprecated
     *
     */
    sh,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: sin Sinhala, Sinhalese
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    si,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: slk Slovak
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    sk,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: slv Slovenian
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    sl,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: smo Samoan
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    sm,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: sna Shona
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    sn,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: som Somali
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    so,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: sqi Albanian
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    sq,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: srp Serbian
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    sr,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: ssw Swati
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ss,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: sot Southern Sotho
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    st,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: sun Sundanese
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    su,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: swe Swedish
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    sv,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: swa Swahili (macrolanguage)
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    sw,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: tam Tamil
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ta,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: tel Telugu
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    te,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: tgk Tajik
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    tg,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: tha Thai
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    th,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: tir Tigrinya
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ti,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: tuk Turkmen
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    tk,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: tgl Tagalog
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    tl,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: tsn Tswana
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    tn,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: ton Tonga (Tonga Islands)
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    to,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: tur Turkish
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    tr,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: tso Tsonga
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ts,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: tat Tatar
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    tt,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: twi Twi
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    tw,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: tah Tahitian
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ty,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: uig Uighur, Uyghur
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ug,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: ukr Ukrainian
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    uk,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: urd Urdu
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ur,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: uzb Uzbek
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    uz,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: ven Venda
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    ve,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: vie Vietnamese
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    vi,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: vol Volapük
     * <p>
     * scope: individual
     * <p>
     * type: constructed
     *
     */
    vo,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: wln Walloon
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    wa,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: wol Wolof
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    wo,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: xho Xhosa
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    xh,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: yid Yiddish
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    yi,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: yor Yoruba
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    yo,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: zha Chuang, Zhuang
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    za,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: zho Chinese
     * <p>
     * scope: macrolanguage
     * <p>
     * type: living
     *
     */
    zh,

    /**
     * {@link ISO_639_3_Code iso 639 3 code}: zul Zulu
     * <p>
     * scope: individual
     * <p>
     * type: living
     *
     */
    zu;
    private ISO_639_3_Code languageCode;

    ISO_639_1_Code() {
    }

    public LanguageCode getLanguageCode() {
        if (this.languageCode == null) {
            this.languageCode = ISO_639_3_Code.getByPart1(this.name()).orElse(null);
        }
        return this.languageCode;
    }

    @Override
    public String toString() {
        return this.getLanguageCode().toString();
    }

    @Override
    public String code() {
        return this.getLanguageCode().code();
    }

    @Override
    public String part3() {
        return this.getLanguageCode().part3();
    }

    @Override
    public String part2B() {
        return this.getLanguageCode().part2B();
    }

    @Override
    public String part2T() {
        return this.getLanguageCode().part2T();
    }

    @Override
    public String part1() {
        return this.getLanguageCode().part1();
    }

    @Override
    public Scope scope() {
        return this.getLanguageCode().scope();
    }

    @Override
    public Type languageType() {
        return this.getLanguageCode().languageType();
    }

    @Override
    public String refName() {
        return this.getLanguageCode().refName();
    }

    @Override
    public String comment() {
        return this.getLanguageCode().comment();
    }

    @Override
    public List<NameRecord> nameRecords() {
        return this.getLanguageCode().nameRecords();
    }

    @Override
    public List<LanguageCode> macroLanguages() {
        return this.getLanguageCode().macroLanguages();
    }

    @Override
    public List<LanguageCode> individualLanguages() {
        return this.getLanguageCode().individualLanguages();
    }

    @Override
    public String getDisplayName(Locale locale) {
        String result = new Locale(code()).getDisplayName(locale);
        if (code().equals(result)) {
            return LanguageCode.super.getDisplayName(locale);
        } else {
            return result;
        }
    }
}
