
package org.meeuw.i18n.languages;

import java.net.URI;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;


/**
 * An enum with all ISO-639-5 language family codes.<p>This enum is automatically generated by class org.meeuw.i18n.languages.test.GenerateEnums from a tab seperated file found on id.loc.gov.<p>
 * 
 */
public enum LanguageFamilyCode
    implements ISO_639_Code
{


    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/aav'>Austro-Asiatic languages</a>
     * 
     */
    aav("http://id.loc.gov/vocabulary/iso639-5/aav", "Austro-Asiatic languages", "austro-asiatiques, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/afa'>Afro-Asiatic languages</a>
     * 
     */
    afa("http://id.loc.gov/vocabulary/iso639-5/afa", "Afro-Asiatic languages", "afro-asiatiques, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/alg'>Algonquian languages</a>
     * 
     */
    alg("http://id.loc.gov/vocabulary/iso639-5/alg", "Algonquian languages", "algonquines, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/alv'>Atlantic-Congo languages</a>
     * 
     */
    alv("http://id.loc.gov/vocabulary/iso639-5/alv", "Atlantic-Congo languages", "atlantique-congo, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/apa'>Apache languages</a>
     * 
     */
    apa("http://id.loc.gov/vocabulary/iso639-5/apa", "Apache languages", "apaches, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/aqa'>Alacalufan languages</a>
     * 
     */
    aqa("http://id.loc.gov/vocabulary/iso639-5/aqa", "Alacalufan languages", "alacalufanes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/aql'>Algic languages</a>
     * 
     */
    aql("http://id.loc.gov/vocabulary/iso639-5/aql", "Algic languages", "algiques, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/art'>Artificial languages</a>
     * 
     */
    art("http://id.loc.gov/vocabulary/iso639-5/art", "Artificial languages", "artificielles, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/ath'>Athapascan languages</a>
     * 
     */
    ath("http://id.loc.gov/vocabulary/iso639-5/ath", "Athapascan languages", "athapascanes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/auf'>Arauan languages</a>
     * 
     */
    auf("http://id.loc.gov/vocabulary/iso639-5/auf", "Arauan languages", "arauanes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/aus'>Australian languages</a>
     * 
     */
    aus("http://id.loc.gov/vocabulary/iso639-5/aus", "Australian languages", "australiennes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/awd'>Arawakan languages</a>
     * 
     */
    awd("http://id.loc.gov/vocabulary/iso639-5/awd", "Arawakan languages", "arawak, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/azc'>Uto-Aztecan languages</a>
     * 
     */
    azc("http://id.loc.gov/vocabulary/iso639-5/azc", "Uto-Aztecan languages", "uto-azt\u00e8ques, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/bad'>Banda languages</a>
     * 
     */
    bad("http://id.loc.gov/vocabulary/iso639-5/bad", "Banda languages", "banda, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/bai'>Bamileke languages</a>
     * 
     */
    bai("http://id.loc.gov/vocabulary/iso639-5/bai", "Bamileke languages", "bamil\u00e9k\u00e9, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/bat'>Baltic languages</a>
     * 
     */
    bat("http://id.loc.gov/vocabulary/iso639-5/bat", "Baltic languages", "baltes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/ber'>Berber languages</a>
     * 
     */
    ber("http://id.loc.gov/vocabulary/iso639-5/ber", "Berber languages", "berb\u00e8res, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/bih'>Bihari languages</a>
     * 
     */
    bih("http://id.loc.gov/vocabulary/iso639-5/bih", "Bihari languages", "langues biharis"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/bnt'>Bantu languages</a>
     * 
     */
    bnt("http://id.loc.gov/vocabulary/iso639-5/bnt", "Bantu languages", "bantou, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/btk'>Batak languages</a>
     * 
     */
    btk("http://id.loc.gov/vocabulary/iso639-5/btk", "Batak languages", "batak, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/cai'>Central American Indian languages</a>
     * 
     */
    cai("http://id.loc.gov/vocabulary/iso639-5/cai", "Central American Indian languages", "am\u00e9rindiennes de l'Am\u00e9rique centrale, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/cau'>Caucasian languages</a>
     * 
     */
    cau("http://id.loc.gov/vocabulary/iso639-5/cau", "Caucasian languages", "caucasiennes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/cba'>Chibchan languages</a>
     * 
     */
    cba("http://id.loc.gov/vocabulary/iso639-5/cba", "Chibchan languages", "chibcha, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/ccn'>North Caucasian languages</a>
     * 
     */
    ccn("http://id.loc.gov/vocabulary/iso639-5/ccn", "North Caucasian languages", "caucasiennes du Nord, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/ccs'>South Caucasian languages</a>
     * 
     */
    ccs("http://id.loc.gov/vocabulary/iso639-5/ccs", "South Caucasian languages", "caucasiennes du Sud, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/cdc'>Chadic languages</a>
     * 
     */
    cdc("http://id.loc.gov/vocabulary/iso639-5/cdc", "Chadic languages", "tchadiques, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/cdd'>Caddoan languages</a>
     * 
     */
    cdd("http://id.loc.gov/vocabulary/iso639-5/cdd", "Caddoan languages", "caddoanes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/cel'>Celtic languages</a>
     * 
     */
    cel("http://id.loc.gov/vocabulary/iso639-5/cel", "Celtic languages", "celtiques, langues; celtes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/cmc'>Chamic languages</a>
     * 
     */
    cmc("http://id.loc.gov/vocabulary/iso639-5/cmc", "Chamic languages", "chames, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/cpe'>Creoles and pidgins, English‑based</a>
     * 
     */
    cpe("http://id.loc.gov/vocabulary/iso639-5/cpe", "Creoles and pidgins, English\u2011based", "cr\u00e9oles et pidgins bas\u00e9s sur l'anglais"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/cpf'>Creoles and pidgins, French‑based</a>
     * 
     */
    cpf("http://id.loc.gov/vocabulary/iso639-5/cpf", "Creoles and pidgins, French\u2011based", "cr\u00e9oles et pidgins bas\u00e9s sur le fran\u00e7ais"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/cpp'>Creoles and pidgins, Portuguese-based</a>
     * 
     */
    cpp("http://id.loc.gov/vocabulary/iso639-5/cpp", "Creoles and pidgins, Portuguese-based", "cr\u00e9oles et pidgins bas\u00e9s sur le portugais"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/crp'>Creoles and pidgins</a>
     * 
     */
    crp("http://id.loc.gov/vocabulary/iso639-5/crp", "Creoles and pidgins", "cr\u00e9oles et pidgins"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/csu'>Central Sudanic languages</a>
     * 
     */
    csu("http://id.loc.gov/vocabulary/iso639-5/csu", "Central Sudanic languages", "soudaniques centrales, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/cus'>Cushitic languages</a>
     * 
     */
    cus("http://id.loc.gov/vocabulary/iso639-5/cus", "Cushitic languages", "couchitiques, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/day'>Land Dayak languages</a>
     * 
     */
    day("http://id.loc.gov/vocabulary/iso639-5/day", "Land Dayak languages", "dayak, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/dmn'>Mande languages</a>
     * 
     */
    dmn("http://id.loc.gov/vocabulary/iso639-5/dmn", "Mande languages", "mand\u00e9, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/dra'>Dravidian languages</a>
     * 
     */
    dra("http://id.loc.gov/vocabulary/iso639-5/dra", "Dravidian languages", "dravidiennes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/egx'>Egyptian languages</a>
     * 
     */
    egx("http://id.loc.gov/vocabulary/iso639-5/egx", "Egyptian languages", "\u00e9gyptiennes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/esx'>Eskimo-Aleut languages</a>
     * 
     */
    esx("http://id.loc.gov/vocabulary/iso639-5/esx", "Eskimo-Aleut languages", "esquimaudes-al\u00e9outiennes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/euq'>Basque (family)</a>
     * 
     */
    euq("http://id.loc.gov/vocabulary/iso639-5/euq", "Basque (family)", "basque (famille)"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/fiu'>Finno-Ugrian languages</a>
     * 
     */
    fiu("http://id.loc.gov/vocabulary/iso639-5/fiu", "Finno-Ugrian languages", "finno-ougriennes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/fox'>Formosan languages</a>
     * 
     */
    fox("http://id.loc.gov/vocabulary/iso639-5/fox", "Formosan languages", "formosanes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/gem'>Germanic languages</a>
     * 
     */
    gem("http://id.loc.gov/vocabulary/iso639-5/gem", "Germanic languages", "germaniques, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/gme'>East Germanic languages</a>
     * 
     */
    gme("http://id.loc.gov/vocabulary/iso639-5/gme", "East Germanic languages", "germaniques orientales, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/gmq'>North Germanic languages</a>
     * 
     */
    gmq("http://id.loc.gov/vocabulary/iso639-5/gmq", "North Germanic languages", "germaniques septentrionales, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/gmw'>West Germanic languages</a>
     * 
     */
    gmw("http://id.loc.gov/vocabulary/iso639-5/gmw", "West Germanic languages", "germaniques occidentales, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/grk'>Greek languages</a>
     * 
     */
    grk("http://id.loc.gov/vocabulary/iso639-5/grk", "Greek languages", "grecques, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/hmx'>Hmong-Mien languages</a>
     * 
     */
    hmx("http://id.loc.gov/vocabulary/iso639-5/hmx", "Hmong-Mien languages", "hmong-mien, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/hok'>Hokan languages</a>
     * 
     */
    hok("http://id.loc.gov/vocabulary/iso639-5/hok", "Hokan languages", "hoka, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/hyx'>Armenian (family)</a>
     * 
     */
    hyx("http://id.loc.gov/vocabulary/iso639-5/hyx", "Armenian (family)", "arm\u00e9nien (famille)"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/iir'>Indo-Iranian languages</a>
     * 
     */
    iir("http://id.loc.gov/vocabulary/iso639-5/iir", "Indo-Iranian languages", "indo-iraniennes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/ijo'>Ijo languages</a>
     * 
     */
    ijo("http://id.loc.gov/vocabulary/iso639-5/ijo", "Ijo languages", "ijo, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/inc'>Indic languages</a>
     * 
     */
    inc("http://id.loc.gov/vocabulary/iso639-5/inc", "Indic languages", "indo-aryennes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/ine'>Indo-European languages</a>
     * 
     */
    ine("http://id.loc.gov/vocabulary/iso639-5/ine", "Indo-European languages", "indo-europ\u00e9ennes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/ira'>Iranian languages</a>
     * 
     */
    ira("http://id.loc.gov/vocabulary/iso639-5/ira", "Iranian languages", "iraniennes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/iro'>Iroquoian languages</a>
     * 
     */
    iro("http://id.loc.gov/vocabulary/iso639-5/iro", "Iroquoian languages", "iroquoises, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/itc'>Italic languages</a>
     * 
     */
    itc("http://id.loc.gov/vocabulary/iso639-5/itc", "Italic languages", "italiques, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/jpx'>Japanese (family)</a>
     * 
     */
    jpx("http://id.loc.gov/vocabulary/iso639-5/jpx", "Japanese (family)", "japonais (famille)"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/kar'>Karen languages</a>
     * 
     */
    kar("http://id.loc.gov/vocabulary/iso639-5/kar", "Karen languages", "karen, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/kdo'>Kordofanian languages</a>
     * 
     */
    kdo("http://id.loc.gov/vocabulary/iso639-5/kdo", "Kordofanian languages", "kordofaniennes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/khi'>Khoisan languages</a>
     * 
     */
    khi("http://id.loc.gov/vocabulary/iso639-5/khi", "Khoisan languages", "kho\u00efsan, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/kro'>Kru languages</a>
     * 
     */
    kro("http://id.loc.gov/vocabulary/iso639-5/kro", "Kru languages", "krou, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/map'>Austronesian languages</a>
     * 
     */
    map("http://id.loc.gov/vocabulary/iso639-5/map", "Austronesian languages", "austron\u00e9siennes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/mkh'>Mon-Khmer languages</a>
     * 
     */
    mkh("http://id.loc.gov/vocabulary/iso639-5/mkh", "Mon-Khmer languages", "m\u00f4n-khmer, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/mno'>Manobo languages</a>
     * 
     */
    mno("http://id.loc.gov/vocabulary/iso639-5/mno", "Manobo languages", "manobo, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/mun'>Munda languages</a>
     * 
     */
    mun("http://id.loc.gov/vocabulary/iso639-5/mun", "Munda languages", "mounda, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/myn'>Mayan languages</a>
     * 
     */
    myn("http://id.loc.gov/vocabulary/iso639-5/myn", "Mayan languages", "maya, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/nah'>Nahuatl languages</a>
     * 
     */
    nah("http://id.loc.gov/vocabulary/iso639-5/nah", "Nahuatl languages", "nahuatl, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/nai'>North American Indian languages</a>
     * 
     */
    nai("http://id.loc.gov/vocabulary/iso639-5/nai", "North American Indian languages", "nord-am\u00e9rindiennes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/ngf'>Trans-New Guinea languages</a>
     * 
     */
    ngf("http://id.loc.gov/vocabulary/iso639-5/ngf", "Trans-New Guinea languages", "trans-nouvelle-guin\u00e9e, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/nic'>Niger-Kordofanian languages</a>
     * 
     */
    nic("http://id.loc.gov/vocabulary/iso639-5/nic", "Niger-Kordofanian languages", "nig\u00e9ro-kordofaniennes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/nub'>Nubian languages</a>
     * 
     */
    nub("http://id.loc.gov/vocabulary/iso639-5/nub", "Nubian languages", "nubiennes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/omq'>Oto-Manguean languages</a>
     * 
     */
    omq("http://id.loc.gov/vocabulary/iso639-5/omq", "Oto-Manguean languages", "otomangue, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/omv'>Omotic languages</a>
     * 
     */
    omv("http://id.loc.gov/vocabulary/iso639-5/omv", "Omotic languages", "omotiques, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/oto'>Otomian languages</a>
     * 
     */
    oto("http://id.loc.gov/vocabulary/iso639-5/oto", "Otomian languages", "otomi, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/paa'>Papuan languages</a>
     * 
     */
    paa("http://id.loc.gov/vocabulary/iso639-5/paa", "Papuan languages", "papoues, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/phi'>Philippine languages</a>
     * 
     */
    phi("http://id.loc.gov/vocabulary/iso639-5/phi", "Philippine languages", "philippines, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/plf'>Central Malayo-Polynesian languages</a>
     * 
     */
    plf("http://id.loc.gov/vocabulary/iso639-5/plf", "Central Malayo-Polynesian languages", "malayo-polyn\u00e9siennes centrales, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/poz'>Malayo-Polynesian languages</a>
     * 
     */
    poz("http://id.loc.gov/vocabulary/iso639-5/poz", "Malayo-Polynesian languages", "malayo-polyn\u00e9siennes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/pqe'>Eastern Malayo-Polynesian languages</a>
     * 
     */
    pqe("http://id.loc.gov/vocabulary/iso639-5/pqe", "Eastern Malayo-Polynesian languages", "malayo-polyn\u00e9siennes orientales, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/pqw'>Western Malayo-Polynesian languages</a>
     * 
     */
    pqw("http://id.loc.gov/vocabulary/iso639-5/pqw", "Western Malayo-Polynesian languages", "malayo-polyn\u00e9siennes occidentales, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/pra'>Prakrit languages</a>
     * 
     */
    pra("http://id.loc.gov/vocabulary/iso639-5/pra", "Prakrit languages", "pr\u00e2krit, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/qwe'>Quechuan (family)</a>
     * 
     */
    qwe("http://id.loc.gov/vocabulary/iso639-5/qwe", "Quechuan (family)", "quechua (famille)"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/roa'>Romance languages</a>
     * 
     */
    roa("http://id.loc.gov/vocabulary/iso639-5/roa", "Romance languages", "romanes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/sai'>South American Indian languages</a>
     * 
     */
    sai("http://id.loc.gov/vocabulary/iso639-5/sai", "South American Indian languages", "sud-am\u00e9rindiennes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/sal'>Salishan languages</a>
     * 
     */
    sal("http://id.loc.gov/vocabulary/iso639-5/sal", "Salishan languages", "salishennes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/sdv'>Eastern Sudanic languages</a>
     * 
     */
    sdv("http://id.loc.gov/vocabulary/iso639-5/sdv", "Eastern Sudanic languages", "soudaniques orientales, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/sem'>Semitic languages</a>
     * 
     */
    sem("http://id.loc.gov/vocabulary/iso639-5/sem", "Semitic languages", "s\u00e9mitiques, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/sgn'>sign languages</a>
     * 
     */
    sgn("http://id.loc.gov/vocabulary/iso639-5/sgn", "sign languages", "langues des signes"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/sio'>Siouan languages</a>
     * 
     */
    sio("http://id.loc.gov/vocabulary/iso639-5/sio", "Siouan languages", "sioux, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/sit'>Sino-Tibetan languages</a>
     * 
     */
    sit("http://id.loc.gov/vocabulary/iso639-5/sit", "Sino-Tibetan languages", "sino-tib\u00e9taines, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/sla'>Slavic languages</a>
     * 
     */
    sla("http://id.loc.gov/vocabulary/iso639-5/sla", "Slavic languages", "slaves, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/smi'>Sami languages</a>
     * 
     */
    smi("http://id.loc.gov/vocabulary/iso639-5/smi", "Sami languages", "sames, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/son'>Songhai languages</a>
     * 
     */
    son("http://id.loc.gov/vocabulary/iso639-5/son", "Songhai languages", "songhai, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/sqj'>Albanian languages</a>
     * 
     */
    sqj("http://id.loc.gov/vocabulary/iso639-5/sqj", "Albanian languages", "albanaises, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/ssa'>Nilo-Saharan languages</a>
     * 
     */
    ssa("http://id.loc.gov/vocabulary/iso639-5/ssa", "Nilo-Saharan languages", "nilo-sahariennes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/syd'>Samoyedic languages</a>
     * 
     */
    syd("http://id.loc.gov/vocabulary/iso639-5/syd", "Samoyedic languages", "samoy\u00e8des, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/tai'>Tai languages</a>
     * 
     */
    tai("http://id.loc.gov/vocabulary/iso639-5/tai", "Tai languages", "tai, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/tbq'>Tibeto-Burman languages</a>
     * 
     */
    tbq("http://id.loc.gov/vocabulary/iso639-5/tbq", "Tibeto-Burman languages", "tib\u00e9to-birmanes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/trk'>Turkic languages</a>
     * 
     */
    trk("http://id.loc.gov/vocabulary/iso639-5/trk", "Turkic languages", "turques, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/tup'>Tupi languages</a>
     * 
     */
    tup("http://id.loc.gov/vocabulary/iso639-5/tup", "Tupi languages", "tupi, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/tut'>Altaic languages</a>
     * 
     */
    tut("http://id.loc.gov/vocabulary/iso639-5/tut", "Altaic languages", "alta\u00efques, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/tuw'>Tungus languages</a>
     * 
     */
    tuw("http://id.loc.gov/vocabulary/iso639-5/tuw", "Tungus languages", "toungouses, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/urj'>Uralic languages</a>
     * 
     */
    urj("http://id.loc.gov/vocabulary/iso639-5/urj", "Uralic languages", "ouraliennes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/wak'>Wakashan languages</a>
     * 
     */
    wak("http://id.loc.gov/vocabulary/iso639-5/wak", "Wakashan languages", "wakashanes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/wen'>Sorbian languages</a>
     * 
     */
    wen("http://id.loc.gov/vocabulary/iso639-5/wen", "Sorbian languages", "sorabes, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/xgn'>Mongolian languages</a>
     * 
     */
    xgn("http://id.loc.gov/vocabulary/iso639-5/xgn", "Mongolian languages", "mongoles, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/xnd'>Na-Dene languages</a>
     * 
     */
    xnd("http://id.loc.gov/vocabulary/iso639-5/xnd", "Na-Dene languages", "na-d\u00e9n\u00e9, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/ypk'>Yupik languages</a>
     * 
     */
    ypk("http://id.loc.gov/vocabulary/iso639-5/ypk", "Yupik languages", "yupik, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/zhx'>Chinese (family)</a>
     * 
     */
    zhx("http://id.loc.gov/vocabulary/iso639-5/zhx", "Chinese (family)", "chinois (famille)"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/zle'>East Slavic languages</a>
     * 
     */
    zle("http://id.loc.gov/vocabulary/iso639-5/zle", "East Slavic languages", "slaves orientales, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/zls'>South Slavic languages</a>
     * 
     */
    zls("http://id.loc.gov/vocabulary/iso639-5/zls", "South Slavic languages", "slaves m\u00e9ridionales, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/zlw'>West Slavic languages</a>
     * 
     */
    zlw("http://id.loc.gov/vocabulary/iso639-5/zlw", "West Slavic languages", "slaves occidentales, langues"),

    /**
     * <a href='http://id.loc.gov/vocabulary/iso639-5/znd'>Zande languages</a>
     * 
     */
    znd("http://id.loc.gov/vocabulary/iso639-5/znd", "Zande languages", "zand\u00e9, langues");
    private final URI uri;
    private final Map<String, String> labels = new HashMap<>();

    LanguageFamilyCode(String uri, String labelEnglish, String labelFrench) {
        this.uri = URI.create(uri);
        labels.put("en", labelEnglish);
        labels.put("fr", labelFrench);
    }

    @Override
    public String code() {
        return this.name();
    }

    @Override
    public Scope scope() {
        return Scope.FAMILY;
    }

    @Override
    public Type languageType() {
        return Type.L;
    }

    public URI uri() {
        return uri;
    }

    @Override
    public String refName() {
        return labels.get("en");
    }

    public Map<String, String> labels() {
        return Collections.unmodifiableMap(labels);
    }

    @Override
    public String toString() {
        return (this.name()+(" ("+(this.refName()+")")));
    }

    public static Optional<LanguageFamilyCode> get(String code) {
        try {
            return Optional.of(LanguageFamilyCode.valueOf(code));
        } catch (IllegalArgumentException _x) {
            return Optional.empty();
        }
    }

}
